config/routes.rb
Rails.application.routes.draw do
  resource :session, controller: "clearance/sessions", only: [:create]
  resources :users, only: [:create]
  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"
  
  resources :devices

  root to: "devices#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/device.rb
class Device < ApplicationRecord
  validates :name, presence: true, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  include Clearance::User

  validates :username, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
end

app/controllers/devices_controller.rb
class DevicesController < ApplicationController
  before_action :set_device, only: [:show, :edit, :update, :destroy]

  def index
    @devices = Device.all
  end

  def show
  end
     
  def new
    @device = Device.new

    respond_to do |format|
      format.html
    end
  end

  def edit
    @device = Device.find(params[:id])
  end
     
  def create
    @device = Device.new(device_params)
    
    respond_to do |format|
      if @device.save
        format.html { redirect_to @device, notice: 'Device was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @device.update(device_params)
        format.html { redirect_to @device, notice: 'Device was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @device.destroy
    
    respond_to do |format|
      format.html { redirect_to device_url, notice: 'Device was successfully destroyed.' }
    end
  end

  
  private

  def set_device
    @device = Device.find(params[:id])
  end

  def device_params
    params.require(:device).permit(:name)
  end
end

app/controllers/users_controller.rb
class UsersController < Clearance::UsersController



  private
  def user_params
    params.require(:user).permit(:username, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/devices/_form.html.erb
<%= form_for(@device) do |f| %>
  <% if @device.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@device.errors.count, "error") %> prohibited this device from being saved:</h2>

      <ul>
      <% @device.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/devices/edit.html.erb
<h1>Editing Device</h1>

<%= render 'form' %>

<%= link_to 'Show', @device %> |
<%= link_to 'Back', devices_path %>

app/views/devices/index.html.erb
<h1>Listing Devices</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

  <% @devices.each do |device| %>
    <tr>
      <td><%= device.name %></td>
      <td><%= link_to ' | Show', device %></td>
      <td><%= link_to ' | Edit', edit_device_path(device) %></td>
      <td><%= link_to ' |Destroy', device, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
<% end %>

</table>

<br/>

<%= link_to 'New Device', new_device_path %>

app/views/devices/new.html.erb
<h1>New Device</h1>

<%= render 'form' %>

<%= link_to 'Back', devices_path %>

app/views/devices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @device.name %>
</p>

<%= link_to 'Edit', edit_device_path(@device) %> |
<%= link_to 'Back', devices_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Device Application</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <% if signed_in? %>
    Signed in as: <%= current_user.email %>
    <%= button_to 'Sign out', sign_out_path, method: :delete %>
  <% else %>
    <%= link_to 'Sign in', sign_in_path %>
  <% end %>
  
  <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<div class="text-field">
  <%= form.label :username %>
  <%= form.text_field :username %>
</div>

<div class="text-field">
  <%= form.label :email %>
  <%= form.text_field :email, type: 'email' %>
</div>

<div class="password-field">
  <%= form.label :password %>
  <%= form.password_field :password %>
</div>

app/views/users/new.html.erb
<div id="clearance" class="sign-up">
  <h2><%= t(".title") %></h2>

  <%= form_for @user do |form| %>
    <%= render partial: '/users/form', object: form %>

    <div class="submit-field">
      <%= form.submit %>
    </div>

    <div class="other-links">
      <%= link_to t(".sign_in"), sign_in_path %>
    </div>
  <% end %>
</div>